MAX_AMOUNT_OF_TRAINING_RUNS = 3

# Movement constant
AMOUNT_OF_BORDER_POINTS = 5
DETECT_MOTION_WINDOW_SIZE = 20

# Movements constants
DIRECTION_WINDOW_SIZE__ELEMENTS = 10
DIRECTION_WINDOW_SIZE__PIXELS = 2
ENDPOINT_WINDOW_SIZE__ELEMENTS = 10
THRESHOLD_VALUE = 10
